# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: afbd03444354b84e29fb197ec088f56c263a9a9deb8ad4925e22cb6da65c2562d261c99e29467efc07533032b0981095dc4c7cc1da06c01352350109a3089346

test:
  secret_key_base: 3b8ca17a639c4c9ef3077eb3e9d999f7a5bc4ce0a01d5a398eb94c5dec7ab43cb218f7b11dbc94dfdc883bf4b6a4c64a803dfd0b69fd523c22d5f8025cd5bbd6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
